### ISSUE TITLE
Provide a subscription model

### ISSUE THREAD

**Issue by FlorianSW** [FlorianSW/server-donation-tool#31]
As a donator
I want to benefit regularly from the perks of a donation package without making a donation manually every month
So that I can focus on playing a game instead of remembering when I should to donate again.

Tasks:
- [x] Add subscription possibility for user
- [x] Make subscription configurable per package
- [x] Send notification to user when subscription was renewed/payed
- [x] Provide a link for a user to view an individual subscription (apart from on PayPal)
- [x] Add a cancel and return URL to the subscription request to PayPal
- [x] Validate incoming webhook events
- [x] Prevent variable price packages to be subscribable
- [x] Provide documentation (subscription configuration in packages, webhook requirement on aPayPal's side, ...)
- [x] (Optional) Provide an overview of active subscriptions of a user (superseded by #32)
- [x] (Optional) prevent a user from having multiple subscriptions of the same package (superseded by #33)
- [x] (Optional) prevent a user from buying a package to which they are subscribed to (superseded by #34)

**Comment by FlorianSW** [comment]
Will be included in the next "formal" release (which will be released depending on when some missing features are implemented).
